#!/sh/bin
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 [local|staging|production]";
    exit 1;
fi
cp /opt/airlol/metadata/config/$1/apache-vhost.conf /opt/airlol/
cp /opt/airlol/metadata/config/$1/ajax.config /opt/airlol/ajax/.config
cp /opt/airlol/metadata/config/$1/page.config /opt/airlol/page/.config
cp /opt/airlol/metadata/config/$1/rest.config /opt/airlol/rest/.config
echo "$1 is successfully deployed"
exit 0;
