#!/sh/bin
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 [local|staging|production]";
    exit 1;
fi
cp /opt/airlol/metadata/config/$1/apache-vhost.conf /opt/airlol/
service apache2 restart
echo "$1 is successfully deployed"
exit 0;
