#!/bin/sh
sshfs -o allow_other peng_shen@mac:/Users/peng_shen/cairyme/ /opt/cairyme
rm /opt/cairyme/page/.config
rm /opt/cairyme/rest/.config
rm /opt/cairyme/ajax/.config
ln -s /opt/cairyme/metadata/config/local/page.config /opt/cairyme/page/.config
ln -s /opt/cairyme/metadata/config/local/rest.config /opt/cairyme/rest/.config
ln -s /opt/cairyme/metadata/config/local/ajax.config /opt/cairyme/ajax/.config
service apache2 restart
